services:
  - type: web
    name: missionfauj-otp-server
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MSG91_WIDGET_ID
        sync: false
      - key: MSG91_TOKEN_AUTH
        sync: false
