services:
  - type: web
    name: missionfauj-otp-server
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MSG91_AUTH_KEY
        sync: false
